The next web
Haywhizzz/TheNextWeb-Clone pull request #1
Opened 2020-06-29 15:28 UTC by eypsrcnuygr

The page is responsive via grid and flexbox.
The page responds to the certain "max-width" properties via media queries.
The validator warned us about lack of headings on the sections but there is no heading on these sections. We tried to use semantics as much as we can.

2020-06-29 18:44 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @eypsrcnuygr & @Haywhizzz  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## Main Page
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Haywhizzz/TheNextWeb-Clone/TheNextWeb/index.html)|
|:---:|:---:|
|![tnw](https://user-images.githubusercontent.com/22345961/86042465-de1f5700-ba4f-11ea-9192-7997530dd8a9.png)|![tnw-clone](https://user-images.githubusercontent.com/22345961/86042475-e4153800-ba4f-11ea-807b-f1c382f9bb67.png)|
- Remove the white border on the page's logo.
- Change the latest news header colour to its appropriate colour  

## Latest Funding Section
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Haywhizzz/TheNextWeb-Clone/TheNextWeb/index.html)|
|:---:|:---:|
|![latest-funding](https://user-images.githubusercontent.com/22345961/86042820-643b9d80-ba50-11ea-9864-d7878f665407.png)|![latest-funding-clone](https://user-images.githubusercontent.com/22345961/86042831-69005180-ba50-11ea-99e7-91da7a09b271.png)|
- Improve the styling on this section to match its source.

## Apps, Gears, Tech Section 
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Haywhizzz/TheNextWeb-Clone/TheNextWeb/index.html)|
|:---:|:---:|
|![apps-gears](https://user-images.githubusercontent.com/22345961/86042882-87664d00-ba50-11ea-9e61-748c9f1dc55b.png)|![apps-gears-clone](https://user-images.githubusercontent.com/22345961/86042901-8c2b0100-ba50-11ea-84b9-b32dd27c368b.png)|
- Improve on the styling on this section as well.

## Latest Deals Section
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Haywhizzz/TheNextWeb-Clone/TheNextWeb/index.html)|
|:---:|:---:|
|![latest-deals](https://user-images.githubusercontent.com/22345961/86043015-bb417280-ba50-11ea-9e2c-bc0bb21de112.png)|![latest-deals-clone](https://user-images.githubusercontent.com/22345961/86043024-bf6d9000-ba50-11ea-9824-3815c55215ae.png)|

- This section also needs some improvements as well

## Footer
|[Source Page](https://thenextweb.com/)|[Clone Page](https://raw.githack.com/Haywhizzz/TheNextWeb-Clone/TheNextWeb/index.html)|
|:---:|:---:|
|![footer](https://user-images.githubusercontent.com/22345961/86043097-dc09c800-ba50-11ea-8b58-b957ee65b47a.png)|![footer-clone](https://user-images.githubusercontent.com/22345961/86043113-e0ce7c00-ba50-11ea-8cfe-9a1e07badaca.png)|
- Some more work needs to be carried out the footer as well.
##
## Other changes required
- The page is not really responsive and the changes are not being reflective as expected. In medium and small screens, the page's navbar needs to have a hamburger icon, this among other changes needs to be worked on. Kindly take note of all the changes needed for this project to be complete. Thank you!
## OPTIONAL
- Validate your markup using this [tool](https://validator.w3.org/nu/#textarea).
##
- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-06-30 09:46 UTC, eypsrcnuygr commented
The white border on the logo is removed,
Appropriate colors applied;
Border-tops applied,
Hamburger menu applied.
Footer two-color applied.

2020-06-30 10:34 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @eypsrcnuygr @Haywhizzz** 
Good job with your new submission for this project :muscle:  
Some improvements are required. Check out the list of changes your page needs:
- [x] This project requires a responsive behavior, it has to look like the source page not only in the large screen size both also in medium and small.
- [x] The small screen size version of your page looks like this:

![](https://i.imgur.com/wcDbRFSl.png)

### Latest news section:
- [x] For medium screen size it aligns 3 articles per row
- [x] For small screen size it aligns 1 article per row and each article has a cover image on the left side and title on the right side of the row.

### Latest funding section:
- [x] For medium screen size it aligns 3 items per row
- [x] For small screen size it aligns 1 item per row

### Categories (Apps, Gear, Tech, etc) section
- [x] For medium screen size it aligns 2 category boxes per row
- [x] For small screen size it aligns 1 category box per row

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-30 13:20 UTC, eypsrcnuygr commented
The latest news section,  latest funding, categories, and the last section are responsive and take the full width of the page for small screens.
Used flex and grid.
Used media queries for 765px and 1112 px.

2020-06-30 15:16 UTC, elmejdki requested changes
# status requires changes :recycle: 
## Hi guys, great job with the desktop view it looks good :clap:  but in other views, it's ruined :red_circle:, I see also that you have skipped most of the [required changes](https://github.com/Haywhizzz/TheNextWeb-Clone/pull/1#pullrequestreview-439887150) by the previous TSE please return back and fix them 

here is how your clone looks on mobile view:
https://raw.githack.com/Haywhizzz/TheNextWeb-Clone/TheNextWeb/index.html

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you are stuck or having any kind of questions don't hesitate to contact me on slack_

2020-07-01 07:45 UTC, eypsrcnuygr commented
The page is responsive, for small, medium, and large screens.
There was a width issue, it was because of the rem unit and flex property. It is solved.

2020-07-01 08:05 UTC, elmejdki requested changes
# status: required changes :recycle: 
## Hello guys it's me again I see that you have a lot to do in your project, first of all, fix your media queries cause your page breaks on some points where it shouldn't, also you need to work on the style see the comments below:

- [x] Fix the header on mobile view:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86217893-fee2cc00-bb77-11ea-92b3-8789df92134a.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86217849-effc1980-bb77-11ea-85aa-e2f494bb7cab.png)

- [x] Fix the header on tablet view also:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86218050-30f42e00-bb78-11ea-9ca1-fc994836be7b.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86217999-220d7b80-bb78-11ea-917c-496b9d2d76b4.png)
 
- [x] on tablet view and smaller screens you need to remove the TNW logo from the main article and display it on the header:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86218178-58e39180-bb78-11ea-865a-c8393de4f996.png)
### original:
![image](https://user-images.githubusercontent.com/34653764/86218221-6567ea00-bb78-11ea-8ea6-6413173e4861.png)

- [x] Latest article should show 4 articles on a row for desktop views:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86218421-a7912b80-bb78-11ea-9b9c-792f5d9e2094.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86218452-b2e45700-bb78-11ea-9fd5-832b8df02e5e.png)

- [ ] on tablet view we should have three articles in a row but you have one messy article:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86218522-d5767000-bb78-11ea-931a-e94bd8deb132.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86218560-e2935f00-bb78-11ea-9ebe-cea47f33e0f9.png)

actually the whole page is messy you need to fix your media queries guys:
![image](https://user-images.githubusercontent.com/34653764/86218873-503f8b00-bb79-11ea-91b3-978cad3fe998.png)

### Please make the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you are stuck or have any questions don't hesitate to contact me on slack_

2020-07-01 10:11 UTC, eypsrcnuygr commented
There are two stages of media queries. One for max-width 806px and then 1025px . We think this cover all the necessary forms of the device widths'. Hope it's will pass.

2020-07-01 11:43 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @eypsrcnuygr @Haywhizzz** 
Nice job with the improvements since my last review :clap: :clap: :clap:  
There are still things to improve in different parts of the page before the project can be approved:
- [x] Make sure you are using the same responsive breakpoints of the original
- [x] You logo in the main news should disappear in medium screen size, your page:

![](https://i.imgur.com/oz5HRrFl.png)

Original page:

![](https://i.imgur.com/rqxOZitl.png)

- [x] latest funding section should use 4 columns in large screen size, your page:

![](https://i.imgur.com/k0Vovpul.png)

Original page:

![](https://i.imgur.com/ffIkw5Bl.png)

- [x] latest funding section should use 3 columns in the medium screen size, your page:

![](https://i.imgur.com/8AoM8rel.png)

The original page:


![](https://i.imgur.com/O3gs79Kl.png)

- [x] Your top three articles should be aligned 1 per row in small screen size (remember, use the same responsive breakpoints of the original). Your page:

![](https://i.imgur.com/wjkHETml.png)

The original:

![](https://i.imgur.com/K8xmA1rl.png)


Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-01 13:31 UTC, eypsrcnuygr commented
At the Next Web Page, the site responds at 1024 and 770px so we did the same. Hope to pass it.

2020-07-01 14:07 UTC, elmejdki requested changes
# status: requires changes :recycle: 
## Hello, guys, it's me again you are almost there need to make just some more changes in order to make your project approved

- Fix the main section on tablet view:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86252961-c5c44f00-bbab-11ea-8900-97741330cca6.png)


### original:
![image](https://user-images.githubusercontent.com/34653764/86252934-be04aa80-bbab-11ea-96f1-75c49e46abbd.png)

- [x] Fix the latest news section in tablet view it should look the same as the original:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86253045-e68ca480-bbab-11ea-8b9d-40d19f1317be.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86253020-decd0000-bbab-11ea-953f-fe3d41e97265.png)

- [x] Fix the last funding section in tablet view
### clone:
![image](https://user-images.githubusercontent.com/34653764/86253100-f906de00-bbab-11ea-9c55-4da01974843f.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86253138-045a0980-bbac-11ea-8e80-1c0f564e2b9c.png)

- [x] Fix the categories section in tablet view:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86253329-4edb8600-bbac-11ea-9214-bc117cb8f7b8.png)

### original:
![image](https://user-images.githubusercontent.com/34653764/86253221-25225f00-bbac-11ea-946b-7b31d070af2d.png)

- [x] Fix the latest deals section on tablet view:
### clone:
![image](https://user-images.githubusercontent.com/34653764/86253381-60bd2900-bbac-11ea-9c43-68faba73ab5e.png)
### original:
![image](https://user-images.githubusercontent.com/34653764/86253406-6adf2780-bbac-11ea-9e6f-5d2d45103143.png)

### Please make the required changes before you request another code review.
# Happy Coding :tophat:

2020-07-01 14:34 UTC, eypsrcnuygr commented
Before we choose 770px as the breakpoint but then it's understood that it should be 768px. So it's changed into 768px. Now for tablet view, it is displayed as the page.

2020-07-02 00:49 UTC, voscarmv requested changes
# Pull Request Under Review by Oscar Mier (TSE) 👨‍💻 🐦

2020-07-02 00:50 UTC, voscarmv requested changes
# Nice work so far. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 
- On the Medium view of the 3 Top Articles section.
1. The TNW logo appears stretched. It's supposed to retain it's normal aspect ratio.
2. The navbar text wraps around. It's supposed to remain on a single line while shrinking the page.
3. The background gradient looks different from the original page.
![image](https://user-images.githubusercontent.com/2739245/86303703-45fdab00-bbd2-11ea-925d-b552ba73930b.png)

- The Latest Funding and Categories sections should have the same width on Large display:
![image](https://user-images.githubusercontent.com/2739245/86303968-0f746000-bbd3-11ea-825f-6a549b1f6890.png)

- They should also have the same width on Medium display:
![image](https://user-images.githubusercontent.com/2739245/86304175-b0fbb180-bbd3-11ea-9b92-e582bfb4213b.png)

- The footer text should be vertically centered and aligned with the TNW logo:
![image](https://user-images.githubusercontent.com/2739245/86304228-dbe60580-bbd3-11ea-95b1-9a28ef9b2fec.png)

### [OPTIONAL]

- Use fonts that are more similar to the fonts from the original page. For this, you may use [Google Fonts](https://fonts.google.com/).

### Submit these changes and request a new code review! 😄 👍 
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-07-02 08:52 UTC, eypsrcnuygr commented
For the background; to make it look like the original page we need to change the HTML structure which we avoid to do.
The latest funding and categories have the same issue as well. When we do this page, we tried different styles just to try ourselves with different properties. Now to align everything we give different margins and padding. That causes some differences on the look while you shrink, but for every type of device it responds well and it is aligned(Tablet view mobile view and big desktop view).

2020-07-02 09:58 UTC, sumancrest0001 requested changes
**Status: Changes required
Hello TEAM,** You have done a good job to create a similar skeleton of the original project and it is responsive too. But we have to work on very basic stylings like margin, padding, font-sizes, etc. I know it is a little bit demotivating to make a number of review requests and make changes. Let's focus on the basics and make sure that the project layout looks similar to the original one. For example, the font-size of the navbar is too small as compared to the original one, categories, and latest funding sections are not aligned properly. Please focus on one section at a time and make changes. 

**After making sure that it looks similar to the original one, submit the project for another review.
If you need any kind of help, I am happy to help you. Just DM me on slack Suman Shrestha.
Happy coding !!!**

2020-07-02 12:57 UTC, eypsrcnuygr commented
Throughout the page, the CSS is arranged using grid. 
Everything is aligned properly. 
Font sizes arranged. Font size for the navbar can't be more otherwise it doesn't fit into one line.
Media queries in 1024 and 768.

2020-07-02 16:34 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello team 👋. Your project looks impressive and you have done a great job implementing the changes. 

### However, we still need to work on some more changes before we can merge.

- Let's fix the top section:
  - The logo is different than the original.
  #### Clone

  ![image](https://user-images.githubusercontent.com/57726348/86386744-d1993980-bcaf-11ea-9087-74749a434404.png)

  #### Original
  
  ![image](https://user-images.githubusercontent.com/57726348/86386808-e4137300-bcaf-11ea-86f8-5788563fb6a0.png)

  - The `tnw-container` class looks different.

  #### Clone

  ![image](https://user-images.githubusercontent.com/57726348/86386860-f42b5280-bcaf-11ea-959b-ce84dafe01bc.png)

  #### Original

  ![image](https://user-images.githubusercontent.com/57726348/86386882-fdb4ba80-bcaf-11ea-9e1a-463003a46f41.png)

  - Let's fix this part:
  
     ![image](https://user-images.githubusercontent.com/57726348/86386390-4ddf4d00-bcaf-11ea-87fe-6a4534a2f72d.png)

- Let's reduce the space here:

  ![image](https://user-images.githubusercontent.com/57726348/86386553-897a1700-bcaf-11ea-9eb1-5018a674faf0.png)

- The social icons in the footer must be links. Please do that.

Apply these changes and request another review.

Happy coding 👨‍💻

2020-07-02 20:17 UTC, eypsrcnuygr commented
The background is the same as the page now
Unnecessary margins deleted
Footer links added

2020-07-02 20:37 UTC, eypsrcnuygr commented
The background is the same as the page now
Unnecessary margins deleted
Footer links added

2020-07-02 20:52 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hi, it's me again 😀. Thanks for making the changes. You are almost there.

- Let's decrease the height of `first-section` class.

- Let's make the `latest funding` section more like the original.

#### Clone
![Annotation 2020-07-03 021503](https://user-images.githubusercontent.com/57726348/86407701-27cba400-bcd3-11ea-9b75-27218511ae62.jpg)

#### Original
![Annotation 2020-07-03 021517](https://user-images.githubusercontent.com/57726348/86407714-2d28ee80-bcd3-11ea-9dc4-f2b3f81d4697.jpg)

- Let's give this section some breathing room. Please add some padding to the list items.
![image](https://user-images.githubusercontent.com/57726348/86407798-56e21580-bcd3-11ea-906c-4f85b2f85c42.png)

- Let's fix this 👇
![Annotation 2020-07-03 021819](https://user-images.githubusercontent.com/57726348/86407944-a32d5580-bcd3-11ea-8762-3adeb09ebfb1.jpg)

#### Here is the original
![Annotation 2020-07-03 021847](https://user-images.githubusercontent.com/57726348/86407963-af191780-bcd3-11ea-9379-0f84dfcfabdd.jpg)

- Same in `latest deals` 👇
![Annotation 2020-07-03 022017](https://user-images.githubusercontent.com/57726348/86408047-e25ba680-bcd3-11ea-8af5-bf53a38c4f28.jpg)

#### Here is the original
![Annotation 2020-07-03 022038](https://user-images.githubusercontent.com/57726348/86408066-e982b480-bcd3-11ea-9d34-4f9f9fbafa8e.jpg)

Apply these changes and request another review.

Happy coding 👨‍💻

2020-07-03 07:19 UTC, eypsrcnuygr commented
Latest funding arranged
Apps gears arranged
The upper part was given more space
There was a yellow sticky nav component before, the site removed it so we did as well

2020-07-03 07:59 UTC, Haywhizzz commented
Latest funding arranged
Apps gears arranged
The upper part was given more space
There was a yellow sticky nav component before, the site removed it so we did as well
The original page structure changes every 1-2 hours and some of the issues pointed out here are due to that.

2020-07-03 10:42 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @Haywhizzz @eypsrcnuygr** 
Good job with your new submission for this project :muscle:  
the appearance of your page almost math the original :clap: :clap: :clap:  
Your project passes most of the requirements. There are just a few details to improve before you can go ahead:
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can create a new class.
- [x]  For categories section, on medium version size, it must align 2 category boxes per row. Your page:

![](https://i.imgur.com/RefMk8fl.png)

The original:

![](https://i.imgur.com/jCCtQGal.png)

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-03 10:42 UTC, andresporras3423 commented on assets/styles.css
> +}
Group selectors with the same style definition, or create a new class.

2020-07-03 10:42 UTC, andresporras3423 commented on assets/styles.css
> +}
Same style definition of the selector on line 289. Group selectors, or create a new class.

2020-07-03 10:42 UTC, andresporras3423 commented on assets/styles.css
> +}
Same style definition of the selector on line 462. Group selectors, or create a new class.

2020-07-03 10:42 UTC, andresporras3423 commented on assets/styles.css
> +  }
Same style definition of the selector on line 642. Group selectors, or create a new class.

2020-07-03 10:42 UTC, andresporras3423 commented on assets/styles.css
> +  }
Same style definition of selectors on lines 780 and 790. Group selectors or create a new class.

2020-07-03 11:12 UTC, eypsrcnuygr commented
For the medium view, the part is arranged as two columns.
Repeated styles are grouped together.

2020-07-03 11:40 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @eypsrcnuygr @Haywhizzz** 
Good job with the improvements for this project :muscle:  
Your project passes most of the requirements :clap: :clap: :clap:  
Just a last detail to solve before you can be approved:
- [x] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can create a new class.

### OPTIONAL

- [x] It's a good practice to have a folder for the images and a different one for the styles

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-03 11:40 UTC, andresporras3423 commented on assets/styles.css
> +}
Group selectors with the same style definition, or create a new class.

2020-07-03 11:56 UTC, eypsrcnuygr commented
Style folder added and repeated style fab is grouped.
Looked for grouped styles, none found.

2020-07-03 12:29 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job team :+1:
- You can now merge the changes.
-  I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-07-03 12:34 UTC, merged